services:
  server:
    image: server
    container_name: server
    command: bash /home/Server/run.sh
    ports:
      - "<YOUR PORT>:80"
      - "<YOUR SSL PORT>:443"
    volumes:
      - <PATH TO YOUR SERVER DATA HERE>:/home/ServerData
      - <PATH TO PUBLIC FILE HERE>:/home/Public